require("config.manager")
require("config.common")
require("config.plugins")
require("config.modules")
require("config.function")
require("config.keymaps")
require("config.commands")
require("config.autocommands")
