local dirname = "config.plugins" .. "."
require(dirname .. "cmp")
require(dirname .. "lualine")
require(dirname .. "treesitter")
require(dirname .. "conform")
require(dirname .. "lightbulb")
require(dirname .. "tree")
require(dirname .. "fzf")
require(dirname .. "telescope")
require(dirname .. "whichkey")
