require("config.plugins.cmp")
require("config.plugins.lualine")
require("config.plugins.treesitter")
require("config.plugins.barbar")
require("config.plugins.conform")
require("config.plugins.lightbulb")
require("config.plugins.tree")
require("config.plugins.fzf")
